### ISSUE TITLE
Missing Branches

### ISSUE THREAD

**Issue by geirman** [AoDev/react-forms-mobx#1]
following through your article, I'd like to `git checkout step-1-basics` as recommended, but it looks like you've not yet pushed that or any other branch up to the repo. Only `master` exists right now.

**Comment by AoDev** [comment]
Hi, they are git tags, not branches. So there is only master with tagged commits for each step.
Did you pull the tags too?

**Comment by geirman** [comment]
Gotcha, my bad. I should have noticed that. _head-bonk_!
